# Generated by Django 3.1.5 on 2021-01-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='question_text',
            new_name='test_text',
        ),
    ]
